### 조회
GET http://localhost:3001/api/challenges?field=NEXTJS&progress=false
Content-Type: application/json


### 상세 조회
GET http://localhost:3001/api/challenges/29
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE3Mjk1NjUzOTgsImV4cCI6MTcyOTU2NjI5OH0.WnvLorQ07f3AXX-HpXwkfXlorYb-Gd2wHGWCbaQo8qM



### 챌린저 내용 변경
PATCH http://localhost:3001/api/challenges/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4LCJpYXQiOjE3MjkyMjQ5ODQsImV4cCI6MTcyOTIyNTg4NH0.XXvvJIKoJIsxIP9n4fkDjPexTeq0FQWfDbNpkut7neU

{
  "title" : "제목 변경",
  "status" : "DELETED",
  "maxParticipants" : 10
}
### 챌린지 전체 조회
GET http://localhost:3001/api/challenges/application?sortBy=status&sortOrder=WAITING
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4LCJpYXQiOjE3MjkyMzIxNzgsImV4cCI6MTcyOTIzMzA3OH0.FMvCppIuc4ngWjwCPFxRTGI6hZH_RaS8Oc_POdeGlWI


### 챌린저 삭제
DELETE  https://docthru-be.vercel.app/api/challenges/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJpYXQiOjE3MjkwNDYxNDgsImV4cCI6MTcyOTA0NzA0OH0.T6spjbtYDAHlxEAKH1FYxfk3e2Ha-utfIg1gA1GbsFE

{
  "message" : "삭제 사유"
}


### 회원가입
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "12341234",
  "nickname" : "test",
  "role" : "ADMIN",
  "grade" : "EXPERT"
}

### 로그인
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "12341234"
}

### URL 조회
GET http://localhost:3001/api/challenges/2/original
Content-Type: application/json


### 챌린지 참여하기
POST http://localhost:3001/api/challenges/18/participations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJpYXQiOjE3Mjk3NjI3MjAsImV4cCI6MTcyOTc2MzYyMH0.5o2CRN0jkyC4nd8N8vC1GcE9P3U7fnJ-mu1SOIbFyHE

### 챌린지 포기
DELETE  http://localhost:3001/api/challenges/60/participations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE3Mjk3NjE5NTIsImV4cCI6MTcyOTc2Mjg1Mn0.iuMqA_951ExE05uMvkLoSZkNf5W4VfBMIPEudEk1TBU


### 챌린지 생성
POST http://localhost:3001/api/challenges/application
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4LCJpYXQiOjE3MjkyMjk3MTksImV4cCI6MTcyOTIzMDYxOX0.SV1H2tca8ouIB7qoYjl60VwJ9FxI8uTy1hrriVl45n0

{
  "title" : "343242314",
  "field" : "API",
  "docType" : "BLOG",
  "description" : "4321412412",
  "docUrl" : "http://www.naver.com",
  "deadline" : "2024-01-01T00:00:00.000Z",
  "maxParticipants" : 5
}

### 챌린지 삭제
DELETE https://docthru-be.vercel.app/api/challenges/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE3Mjk0OTY3MTQsImV4cCI6MTcyOTQ5NzYxNH0.eLoj87lCvS2CqOSy2OBAUK-LEufVfE7LSm3BBYYcesM

### 대댓글 작성
POST http://localhost:3001/feedbacks/1/replies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4LCJpYXQiOjE3MjkyMzIxNzgsImV4cCI6MTcyOTIzMzA3OH0.FMvCppIuc4ngWjwCPFxRTGI6hZH_RaS8Oc_POdeGlWI

{
  "feedbackId" : 1,
  "content" : "대댓글 작성"
}


### 챌린지 전체 조회( 챌린지 신청 관리)
GET http://localhost:3001/api/challenges/application?sortBy=status&sortOrder=WAITING&keyword=테스트
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE3Mjk2NDk5NTksImV4cCI6MTcyOTY1MDg1OX0.S3cRHFCAEBpg26xofRCgPF1lRMkzi6CaruNmUDuwnJU
